/**
 * Process-exit primitives (ExitError, runMain, terminateNow) plus the
 * json-error-mode and contract-version cells.
 *
 * Must import nothing but `node:fs` and `./exit-code-registry.cjs` — this
 * source is emitted to TWO locations, gsd-core/bin/lib/cli-exit.cjs (tsc
 * build output) and scripts/lib/cli-exit.cjs (a generated, committed
 * artifact regenerated by scripts/gen-scripts-cli-exit.cjs), and the latter
 * must load on an unbuilt clone before anything under ./lib exists. The
 * registry require is safe here for the same reason: scripts/gen-exit-code-
 * registry.cjs (ADR-3889 Phase 1/2, #3905/#3906) dual-emits its OWN sibling
 * artifact, exit-code-registry.cjs, into both of these exact locations, so
 * a relative `./exit-code-registry.cjs` resolves next to whichever copy of
 * this module loaded it.
 */
import fs from 'node:fs';
// eslint-disable-next-line @typescript-eslint/no-require-imports
import exitCodeRegistryModule = require('./exit-code-registry.cjs');
// Called only as exitCodeRegistryModule.exitCodeFor(...), never destructured:
// @typescript-eslint/unbound-method flags a bare function-typed property
// pulled off an object at the point of destructuring, since a detached
// reference COULD be called with the wrong `this` — keeping the member
// access qualified sidesteps that regardless of whether the callee ever
// actually touches `this` (it does not; exitCodeFor is pure).
const exitCodeFor = (name: string): number => exitCodeRegistryModule.exitCodeFor(name);

/**
 * The wire value `runMain` stamps into its structured envelope. Declared HERE,
 * not in io.cts, because this module must not import anything (see the module
 * header): io.cts builds ERROR_REASON.SDK_FAIL_FAST from this constant, so the
 * two surfaces share ONE definition rather than two literals kept in step by a
 * parity test.
 */
const EXIT_ENVELOPE_REASON = 'sdk_fail_fast' as const;

/**
 * Process-level flag: when true, error paths emit structured JSON to stderr
 * instead of plain text. Set by gsd-tools.cjs when the CLI is invoked with
 * `--json-errors`; re-exported by io.cts, which is where most callers reach it.
 *
 * Held in a Symbol-keyed cell on globalThis rather than in module scope, and
 * that is load-bearing: this module is emitted to TWO locations
 * (gsd-core/bin/lib/cli-exit.cjs and the generated scripts/lib/cli-exit.cjs),
 * so a process that loads both would get two independent module instances. A
 * module-level `let` would give them two independent flags — one copy could
 * think json mode is on while the other thought it was off, which is exactly
 * the divergence class ADR-3889 exists to remove. One cell, keyed by a
 * registry Symbol, makes that unrepresentable.
 */
const JSON_ERROR_MODE_KEY = Symbol.for('gsd.exit.jsonErrorMode');

function setJsonErrorMode(v: unknown): void {
  (globalThis as unknown as Record<symbol, boolean>)[JSON_ERROR_MODE_KEY] = !!v;
}

function getJsonErrorMode(): boolean {
  return (globalThis as unknown as Record<symbol, boolean>)[JSON_ERROR_MODE_KEY] === true;
}

/** The single registered name code 2 may ever be produced for (ADR-3889 §1). */
const HOOK_DENY_NAME = 'HOOK_DENY';
const HOOK_DENY_CODE = exitCodeFor(HOOK_DENY_NAME);

type ContractVersion = 'v1' | 'v2';

/**
 * Currently-resolved exit-contract version (ADR-3889 §4). Held in a
 * Symbol-keyed globalThis cell rather than a module-level `let`, for the
 * exact reason JSON_ERROR_MODE_KEY is (see its comment above): this module
 * is emitted to two locations and thus loaded as two independent module
 * instances in any process that requires both, so a module-level variable
 * would let those two instances disagree about which contract is active.
 * `resolveContractVersion` is the only writer; `terminateNow`/`runMain`
 * read it internally when projecting a declared outcome.
 */
const CONTRACT_VERSION_KEY = Symbol.for('gsd.exit.contractVersion');

function setContractVersion(v: ContractVersion): void {
  (globalThis as unknown as Record<symbol, ContractVersion>)[CONTRACT_VERSION_KEY] = v;
}

/**
 * Resolve the active exit-contract version, wiring the ambient process to the
 * two terminators (ADR-3889 §4/§3). Mirrors how JSON_ERROR_MODE_KEY already
 * works: a process-global cell means no entrypoint needs per-call wiring, so
 * a `scripts/` tool or a hook gets the same behaviour as `gsd-tools` without
 * this module touching either (P8 owns `gsd-tools`; P7 owns hooks).
 *
 * Precedence: if the cell already holds an explicit version, that wins —
 * this is what lets `setContractVersion` override the ambient process (a
 * later `GSD_EXIT_CONTRACT=v2` in the same process must NOT unseat an
 * explicit `setContractVersion('v1')` call). Otherwise resolve from argv/env
 * via `resolveContractVersion`, which itself persists the result into the
 * cell — so this is a one-time resolution per process; every later read is
 * just the cached cell value. An invalid ambient value (e.g. `v3`) is NOT
 * softened to a silent v1 here: `resolveContractVersion` throws, and that
 * throw propagates — swallowing it would reintroduce the "nothing fails with
 * success" defect ADR-3889 exists to close, on the very selector meant to
 * demonstrate the fix. Absent both flag and env, resolution still yields
 * 'v1' (the documented default) and that too gets memoized.
 */
function getContractVersion(): ContractVersion {
  const cached = (globalThis as unknown as Record<symbol, ContractVersion | undefined>)[CONTRACT_VERSION_KEY];
  if (cached === 'v1' || cached === 'v2') return cached;
  return resolveContractVersion({ argv: process.argv, env: process.env });
}

/**
 * Project a declared outcome onto an integer exit code for a given contract
 * version. Pure and total over its own input space: throws for anything not
 * an exact-case registered name (mirrors exitCodeFor's contract) or an
 * unrecognized version — it never returns undefined/NaN.
 *
 * PASS/FAIL and every registered name project IDENTICALLY under v1 and v2
 * (registered names are version-invariant) — the sole exception is DEGRADED:
 *
 *   v1: DEGRADED -> 0.  Deliberate, NOT a bug: ADR-2980 ratified 60
 *       `output({error})` call sites that already exit 0 on a payload-carried
 *       error, and ADR-2980's own "Revisit if" clause is what ADR-3889 §4
 *       answers — normalizing this to a non-zero code was explicitly
 *       DECLINED there on measured blast radius. A future reader must not
 *       "fix" this to look more consistent with v2; the inconsistency IS the
 *       compatibility boundary.
 *   v2: DEGRADED -> exitCodeFor('DEGRADED') (80). Looked up through the
 *       registry, never hardcoded, so a re-allocation of DEGRADED's code
 *       cannot silently desync this projection from the shipped table.
 */
function projectOutcome(outcome: unknown, version: unknown): number {
  if (typeof outcome !== 'string' || outcome.length === 0) {
    throw new Error(`projectOutcome: outcome must be a non-empty string, received ${JSON.stringify(outcome)}`);
  }
  if (version !== 'v1' && version !== 'v2') {
    throw new Error(`projectOutcome: version must be 'v1' or 'v2', received ${JSON.stringify(version)}`);
  }
  if (outcome === 'PASS') return 0;
  if (outcome === 'FAIL') return 1;
  if (outcome === 'DEGRADED') return version === 'v1' ? 0 : exitCodeFor('DEGRADED');
  // Any other registered name: version-invariant, resolved through the
  // registry (throws for anything unregistered/empty/non-string/wrong-case —
  // exitCodeFor's own contract, which this function inherits verbatim).
  return exitCodeFor(outcome);
}

const EXIT_CONTRACT_FLAG_PREFIX = '--exit-contract=';

/** Scan argv for the FIRST `--exit-contract=<value>` token; undefined if absent. */
function findExitContractFlag(argv: readonly string[]): string | undefined {
  for (const arg of argv) {
    if (typeof arg === 'string' && arg.startsWith(EXIT_CONTRACT_FLAG_PREFIX)) {
      return arg.slice(EXIT_CONTRACT_FLAG_PREFIX.length);
    }
  }
  return undefined;
}

/**
 * Resolve which exit-contract version is active from argv/env, per ADR-3889
 * §4, and persist it to the shared contract-version cell so a later
 * `terminateNow`/`runMain` call (through EITHER module copy) projects
 * against it without re-parsing argv/env itself.
 *
 * Precedence: an explicit `--exit-contract=<v>` flag BEATS
 * `GSD_EXIT_CONTRACT`, in both directions (flag=v1 + env=v2 -> v1; flag=v2 +
 * env=v1 -> v2). Neither present -> 'v1' (the documented default). An empty
 * env var reads as UNSET, not as an explicit empty selection — a shell that
 * exports `GSD_EXIT_CONTRACT=` with nothing after the `=` must not silently
 * select a version.
 *
 * Casing is decided, not accidental: only the exact lowercase tokens `v1`/
 * `v2` are accepted (matching every example in ADR-3889 and this module's own
 * usage docs, both of which write `v2` never `V2`). Anything else recognized
 * as PRESENT but not a valid version — `v3`, `garbage`, or an explicitly
 * empty flag value (`--exit-contract=`) — THROWS rather than silently
 * defaulting to v1. A selector for a contract whose whole thesis is "nothing
 * fails with success" must not itself fail open.
 */
function resolveContractVersion(opts: { argv?: readonly string[]; env?: NodeJS.ProcessEnv } = {}): ContractVersion {
  const argv = opts.argv ?? process.argv;
  const env = opts.env ?? process.env;

  const flagValue = findExitContractFlag(argv);
  const rawEnvValue = env.GSD_EXIT_CONTRACT;
  const envValue = rawEnvValue === undefined || rawEnvValue === '' ? undefined : rawEnvValue;

  const selected = flagValue !== undefined ? flagValue : envValue;

  let resolved: ContractVersion;
  if (selected === undefined) {
    resolved = 'v1';
  } else if (selected === 'v1' || selected === 'v2') {
    resolved = selected;
  } else {
    throw new Error(
      `resolveContractVersion: unrecognized exit-contract version ${JSON.stringify(selected)} `
      + `(expected 'v1' or 'v2')`,
    );
  }

  setContractVersion(resolved);
  return resolved;
}

/**
 * Error carrying a process exit code. CLI logic throws this instead of calling
 * process.exit() (banned by n/no-process-exit); runMain() translates it into
 * process.exitCode at the entrypoint.
 */
class ExitError extends Error {
  code: number;
  hasUserMessage: boolean;
  constructor(code = 1, message?: string) {
    super(message === undefined ? `process exit ${code}` : message);
    this.name = 'ExitError';
    this.code = code;
    this.hasUserMessage = message !== undefined;
  }
}

/**
 * Run a CLI main and translate its outcome into process.exitCode (never
 * process.exit, so n/no-process-exit stays satisfied; output flushes and
 * process.on('exit') cleanup still fires — this is precisely why runMain and
 * terminateNow are two different functions: drain-then-exit vs write-then-
 * terminate). main may be sync or async. Every arm below except the new
 * string one is UNCHANGED from before ADR-3889 Phase 2:
 *   number return   -> process.exitCode = it (unchanged)
 *   string return   -> NEW: process.exitCode = projectOutcome(result, getContractVersion())
 *   thrown ExitError -> process.exitCode = err.code (+ stderr err.message if hasUserMessage && code!=0) (unchanged)
 *   other throw -> when json-error mode is active, emits structured { ok:false, reason, message }
 *                  to stderr; otherwise writes raw stack trace. exit code = 1 in either case. (unchanged)
 */
function runMain(main: () => number | string | void | Promise<number | string | void>): void {
  Promise.resolve()
    .then(() => main())
    .then((result) => {
      if (typeof result === 'number') { process.exitCode = result; return; }
      if (typeof result === 'string') { process.exitCode = projectOutcome(result, getContractVersion()); return; }
    })
    .catch((err: unknown) => {
      if (err instanceof ExitError) {
        if (err.hasUserMessage && err.code !== 0) process.stderr.write(`${err.message}\n`);
        process.exitCode = err.code;
        return;
      }
      if (getJsonErrorMode()) {
        const e = err as Error;
        const payload = JSON.stringify({
          ok: false,
          reason: EXIT_ENVELOPE_REASON,
          message: (e && e.message) ? e.message : String(err),
        }) + '\n';
        fs.writeSync(2, payload);
      } else {
        const e = err as Error;
        process.stderr.write(`${e && e.stack ? e.stack : String(err)}\n`);
      }
      process.exitCode = 1;
    });
}

/**
 * Write `payload` fully to fd 1 (and, for a deny, fd 2 too) and terminate the
 * process IMMEDIATELY with `outcome` projected through the current contract
 * version. This is write-then-terminate, the other half of ADR-3889 §3's
 * "two terminators over one registry": hooks fire from contexts (e.g. a
 * `setTimeout` stdin-timeout guard) where `process.exitCode = N; return;`
 * terminates nothing, so they need an immediate, synchronous exit — the
 * exact gap `eslint.config.mjs:563-582` documents for `hooks/**`.
 *
 * This is THE ONLY sanctioned `process.exit` call site in the repo, and the
 * only place exit code 2 can be produced: 2 is reserved to the hook-adapter
 * protocol (ADR-3889 §1), and the registry's own one-owner rule already
 * guarantees no other registered name resolves to it — the check below is a
 * defense-in-depth assertion of that invariant, not the sole thing enforcing
 * it.
 *
 * @param outcome - declared outcome name, projected via projectOutcome.
 * @param payload - JSON-serializable value written to fd 1 (and, on a deny,
 *   fd 2 too — Kimi's native hook bus feeds stderr, not stdout, back to the
 *   model on exit 2, per hooks/gsd-write-guard.js's emitBlock).
 */
function terminateNow(outcome: string, payload: unknown): never {
  const version = getContractVersion();
  const projected = projectOutcome(outcome, version);

  if (projected === HOOK_DENY_CODE && outcome !== HOOK_DENY_NAME) {
    throw new Error(
      `terminateNow: exit code ${HOOK_DENY_CODE} is reserved to the ${HOOK_DENY_NAME} outcome; `
      + `got outcome ${JSON.stringify(outcome)}`,
    );
  }

  // m2 (round 5, hooks/gsd-write-guard.js:159-175): emission must itself be
  // exception-safe. A failed write (EPIPE, a full pipe buffer, a throwing
  // fs.writeSync in a test) must NOT change the exit code — if it propagated
  // out of this function, a caller whose payload could not be delivered
  // would fall into ITS OWN outer catch and fail OPEN, which is the exact
  // outcome the fail-closed branches this function serves exist to prevent.
  // The decision to terminate with `projected` stands regardless of whether
  // the payload could be delivered.
  try {
    // fs.writeSync, never process.stdout.write: pipe writes via
    // process.stdout/stderr are async on Windows, and process.exit() below
    // does not wait for them to flush — a truncated payload is a silent
    // half-emission. Looped over a Buffer (not a bare string call) so a
    // payload larger than the destination pipe's buffer — where a single
    // write() syscall can legitimately return fewer bytes written than
    // requested — still arrives whole rather than truncated.
    const buf = Buffer.from(JSON.stringify(payload), 'utf8');
    let offset = 0;
    while (offset < buf.length) {
      offset += fs.writeSync(1, buf, offset, buf.length - offset);
    }
    if (projected === HOOK_DENY_CODE) {
      let stderrOffset = 0;
      while (stderrOffset < buf.length) {
        stderrOffset += fs.writeSync(2, buf, stderrOffset, buf.length - stderrOffset);
      }
    }
  } catch {
    // Emission failed; the exit code decision still stands (see above).
  }

  // n/no-process-exit is not registered for src/**/*.cts (see the ADR-3889
  // reference note in the module header) and both compiled .cjs copies of
  // this module are lint-ignored build/generated artifacts, so no disable
  // directive is needed here for the one sanctioned process.exit call site.
  process.exit(projected);
}

export = {
  ExitError,
  runMain,
  setJsonErrorMode,
  getJsonErrorMode,
  EXIT_ENVELOPE_REASON,
  projectOutcome,
  resolveContractVersion,
  getContractVersion,
  terminateNow,
};
